### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/metalEximus#12]
закоментувати в меню адмінки все що не треба замовнику

**Comment by nikolayr1** [comment]
давай закоментим некоторые пункты и подпункты меню в админке?
![image](https://cloud.githubusercontent.com/assets/11279857/9150113/57edf926-3dda-11e5-89d6-ae37b72c9e43.png)

**Comment by dumbik** [comment]
я так понимаю, что ты даже не смотрел как выводятся эти пункты в админке)) там не все так просто. и подпункты не за чем скрывать, если будет скрыт пункт (короче там просто нужно оставить 2 категории, как по мне: "каталог" и "сайт").
короче я пытался это сделать, но у меня не получилось
