### ISSUE TITLE
вставить статьи

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metalEximus#14]
Вставить правильные статьи, те что писали даша и настч

**Comment by Wilvarin** [comment]
еще Дашина статья.

**Comment by Wilvarin** [comment]
Statya_reshetki_1.doc
в документах диалога TQG есть

**Comment by Wilvarin** [comment]
не вставлена 1 статья. 
а те что есть немного не правильно вставлены. 
http://prntscr.com/83rz0y
дублируется начало. 
статья формируется  так "краткое описание + полное описание" 
тобишь не нужно вставлять в полное описание то что уже есть в кратком.

**Comment by nikolayr1** [comment]
поправлю краткое описание
