### ISSUE TITLE
Исправить ссылки на категории и на товары

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/metalEximus#25]
везде на главной и в категориях

**Comment by nikolayr1** [comment]
блин, все не так просто

**Comment by nikolayr1** [comment]
но дело в стилях. когда их отключаешь, то все работает.

**Comment by nikolayr1** [comment]
ааа. все. у .pager position: relative/ не понимаю пока как это ломало все, но я сейчас поправлю

**Comment by nikolayr1** [comment]
я кароч снова все сломал. хахах) 1337 ракло-дестроер
