### ISSUE TITLE
фансибокс для товаров которые подгружаются при прокрутке. 

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/metalEximus#27]
не корректно работает фансибокс для тех товаров что были не на первой странице (которые погружаются при прокрутке)
http://prntscr.com/88lt5h

**Comment by dumbik** [comment]
вот хуйны

**Comment by dadakax** [comment]
Объясняю почему не работал, очень важный момент, при работе с ajax часто с этим проблемы. Когда вы добавляете новые dom-элементы, события, которые вы прописали ранее для них, работать не будут, нужно эти события заново объявлять. Но лучше изначально юзать .on() http://api.jquery.com/on/
