### ISSUE TITLE
цены. в гривнах и без копеек

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/metalEximus#5]
На всём сайте

**Comment by Wilvarin** [comment]
уже в гривнах.

**Comment by nikolayr1** [comment]
антоха вроде бы хотел в базе копеечки убрать

**Comment by dumbik** [comment]
в базе антоха не хотел копеечки убрать. я вчера соломе рассказывал как это
скорее всего можно убрать. в базе это типа флоат, поэтому при выводе цены
можно в коде написать (int) и возможно оно норм будет целое число выводить,
так что можете сами попробовать это сделать

2015-08-06 13:48 GMT+03:00 Nikolay_R <notifications@github.com>:
