### ISSUE TITLE
Почта

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/metalEximus#8]
Потрібно розібратися  з поштою,
Замовник хоче, щоб вона була на його домені.
Думаю, Це дозволяє зробити хостинг.

**Comment by nikolayr1** [comment]
в смысле он хочет почту mail@metal-expert.com.ua ?

**Comment by nikolayr1** [comment]
уточни, пожалуйста, задачу.

**Comment by successus** [comment]
так

**Comment by nikolayr1** [comment]
не могу зайти на хостинг, чтобы настроить почту.
![image](https://cloud.githubusercontent.com/assets/11279857/9129944/da13512c-3cee-11e5-91d1-718ca609a696.png)

**Comment by nikolayr1** [comment]
сделали почту vadimbal@metal-expert.com.ua(или как-то так). на нее можно получать письма. отправленные с нее письма не доходят до получателя.

**Comment by dumbik** [comment]
почта у этого сервиса полная жопа, примерно так и можно обьяснить Вадиму, так что пусть пользуется обычной нормальной почтой, которая работает хоть нормально
